# Generated by Django 4.2.7 on 2024-01-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_allimages_text_alter_allimages_text_uk'),
    ]

    operations = [
        migrations.AddField(
            model_name='allimages',
            name='title_uk',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
