# Generated by Django 4.2.7 on 2023-11-23 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_image_post_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='img',
        ),
        migrations.AddField(
            model_name='post',
            name='img_main',
            field=models.ImageField(default='images/default.svg', upload_to='images'),
        ),
    ]
