# Generated by Django 4.2.7 on 2024-01-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_allimages_title_uk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alllinks',
            name='category',
            field=models.CharField(blank=True, choices=[('social_links', 'social_links'), ('site_links', 'site_links'), ('footer_links', 'footer_links'), ('mobile', 'mobile')], max_length=12),
        ),
    ]
