# Generated by Django 4.2.7 on 2023-11-27 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
