# Generated by Django 4.2.7 on 2023-11-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_sociallinks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sociallinks',
            options={'verbose_name': 'Social Link', 'verbose_name_plural': 'Social links'},
        ),
        migrations.AddField(
            model_name='sociallinks',
            name='alt',
            field=models.TextField(default='alt', max_length=250),
        ),
    ]
