# Generated by Django 4.2.7 on 2023-11-28 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_post_img_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='img_email',
        ),
        migrations.RemoveField(
            model_name='post',
            name='img_github',
        ),
        migrations.RemoveField(
            model_name='post',
            name='img_it',
        ),
        migrations.RemoveField(
            model_name='post',
            name='img_linkedin',
        ),
    ]
