# Generated by Django 4.2.7 on 2023-11-30 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='img',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
