# Generated by Django 4.2.7 on 2023-11-30 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_services_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='img',
            field=models.ImageField(blank=True, upload_to='img_services'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='img',
            field=models.ImageField(blank=True, upload_to='img_skills'),
        ),
        migrations.AlterField(
            model_name='sociallinks',
            name='img',
            field=models.ImageField(blank=True, upload_to='img_social_links'),
        ),
    ]
