# Generated by Django 4.2.7 on 2023-12-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_rename_sociallinks_allimages_alter_allimages_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='allimages',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
