# Generated by Django 4.2.7 on 2023-12-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_allimages_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='allimages',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='allimages',
            name='category',
            field=models.CharField(choices=[('sociallinks', 'Sochial links'), ('services', 'Services'), ('skills', 'Skills'), ('learning', 'learning'), ('link', 'link')], max_length=11),
        ),
        migrations.AlterField(
            model_name='allimages',
            name='img',
            field=models.ImageField(blank=True, upload_to='db_images'),
        ),
        migrations.AlterField(
            model_name='allimages',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
