# Generated by Django 4.2.7 on 2023-12-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_allimages_link_alter_allimages_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioSites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('img', models.ImageField(blank=True, upload_to='db_images')),
                ('link', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Portfolio site',
                'verbose_name_plural': 'Portfolio sites',
            },
        ),
        migrations.RemoveField(
            model_name='allimages',
            name='link',
        ),
        migrations.AlterField(
            model_name='allimages',
            name='category',
            field=models.CharField(choices=[('sociallinks', 'Sochial links'), ('services', 'Services'), ('skills', 'Skills'), ('learning', 'learning')], max_length=11),
        ),
    ]
