# Generated by Django 4.2.7 on 2023-12-18 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_portfoliosites_remove_allimages_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfoliosites',
            old_name='link',
            new_name='site_link',
        ),
    ]
