# Generated by Django 4.2.7 on 2023-12-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_portfoliosites_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliosites',
            name='site_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
