# Generated by Django 4.2.7 on 2023-12-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_portfoliosites_site_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allimages',
            name='category',
            field=models.CharField(choices=[('sociallinks', 'Sochial links'), ('services', 'Services'), ('skills', 'Skills'), ('learning', 'learning'), ('footer_links', 'footer_links')], max_length=12),
        ),
    ]
