# Generated by Django 4.2.7 on 2023-12-22 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_alter_allimages_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PortfolioSites',
            new_name='AllLinks',
        ),
    ]
