# Generated by Django 4.2.7 on 2023-12-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_rename_portfoliosites_alllinks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alllinks',
            options={'verbose_name': 'Link', 'verbose_name_plural': 'All links'},
        ),
        migrations.AddField(
            model_name='alllinks',
            name='category',
            field=models.CharField(choices=[('sochial_link', 'sochial_link'), ('site_link', 'site_link'), ('footer_link', 'footer_link')], default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='allimages',
            name='category',
            field=models.CharField(choices=[('services', 'Services'), ('skills', 'Skills'), ('learning', 'learning')], max_length=11),
        ),
    ]
