# Generated by Django 4.2.7 on 2023-12-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_alllinks_options_alllinks_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alllinks',
            old_name='site_link',
            new_name='link',
        ),
        migrations.AlterField(
            model_name='allimages',
            name='img',
            field=models.ImageField(blank=True, upload_to='all_images'),
        ),
        migrations.AlterField(
            model_name='alllinks',
            name='category',
            field=models.CharField(choices=[('social_link', 'social_link'), ('site_link', 'site_link'), ('footer_link', 'footer_link')], max_length=12),
        ),
    ]
