# Generated by Django 4.2.7 on 2023-12-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_rename_site_link_alllinks_link_alter_allimages_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alllinks',
            name='category',
            field=models.CharField(choices=[('social_links', 'social_links'), ('site_links', 'site_links'), ('footer_links', 'footer_links')], max_length=12),
        ),
    ]
