# Generated by Django 4.2.7 on 2023-12-26 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_callback'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Callback',
            new_name='ContactForm',
        ),
        migrations.AlterModelOptions(
            name='contactform',
            options={'verbose_name': 'Contact form'},
        ),
    ]
