# Generated by Django 4.2.7 on 2023-12-26 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_rename_callback_contactform_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactForm',
        ),
    ]
