# Generated by Django 4.2.7 on 2023-11-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_post_img_post_img_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img_email',
            field=models.ImageField(default='images/default.svg', upload_to='images'),
        ),
        migrations.AddField(
            model_name='post',
            name='img_github',
            field=models.ImageField(default='images/default.svg', upload_to='images'),
        ),
        migrations.AddField(
            model_name='post',
            name='img_linkedin',
            field=models.ImageField(default='images/default.svg', upload_to='images'),
        ),
    ]
