# Generated by Django 4.2.7 on 2023-11-28 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_sociallinks_options_sociallinks_alt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sociallinks',
            name='alt',
        ),
    ]
